import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { useSelector } from 'react-redux';
const Intro = () => {
    const navigate = useNavigate();
    const authStatus = useSelector((state) => state.auth.status);
    return (_jsxs("div", { className: "relative", children: [_jsx("div", { className: 'h-[5vh] xl:h-[10vh] w-full' }), _jsxs("div", { className: "flex-grow flex flex-col items-center justify-center w-full px-4", children: [_jsxs("div", { className: "flex flex-col gap-y-3 font-bold text-black text-4xl xl:text-6xl max-w-6xl items-center justify-center text-center", children: [_jsxs("h1", { className: "leading-tight", children: [_jsx("span", { className: "text-blue-700", children: "AI-Powered" }), " Financial Insights to ", _jsx("span", { className: "text-blue-700", children: "Automate" }), ","] }), _jsxs("h1", { className: "leading-tight", children: ["Optimize and ", _jsx("span", { className: "bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent", children: "Dominate" }), " Your Wealth"] })] }), _jsxs("div", { className: 'flex flex-col gap-y-1 pt-6 lg:pt-10 text-xl xl:text-2xl w-full max-w-4xl justify-center items-center text-center text-gray-600', children: [_jsx("p", { children: "Transform your financial future with intelligent automation and personalized insights." }), _jsx("p", { children: "Simplify wealth management and make smarter investment decisions effortlessly." })] }), _jsx("div", { className: "flex flex-col sm:flex-row gap-4 pt-8 lg:pt-12 items-center", children: authStatus ? (_jsx("button", { onClick: () => navigate('/dashboard'), className: "bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white font-semibold py-4 px-8 rounded-full shadow-lg transform hover:scale-105 transition-all duration-200", children: "Go to Dashboard" })) : (_jsxs(_Fragment, { children: [_jsx("button", { onClick: () => navigate('/signup'), className: "bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white font-semibold py-4 px-8 rounded-full shadow-lg transform hover:scale-105 transition-all duration-200", children: "Get Started Free" }), _jsx("button", { onClick: () => navigate('/login'), className: "border-2 border-blue-600 text-blue-600 hover:bg-blue-600 hover:text-white font-semibold py-4 px-8 rounded-full transition-all duration-200", children: "Sign In" })] })) }), _jsxs("div", { className: "flex flex-col items-center pt-12 lg:pt-16", children: [_jsx("p", { className: "text-sm text-gray-500 mb-4", children: "Trusted by 10,000+ users worldwide" }), _jsxs("div", { className: "flex items-center space-x-8 opacity-60", children: [_jsx("div", { className: "text-2xl font-bold text-gray-400", children: "\uD83C\uDFE6" }), _jsx("div", { className: "text-2xl font-bold text-gray-400", children: "\uD83D\uDCCA" }), _jsx("div", { className: "text-2xl font-bold text-gray-400", children: "\uD83D\uDD12" }), _jsx("div", { className: "text-2xl font-bold text-gray-400", children: "\uD83D\uDCC8" })] })] })] })] }));
};
export default Intro;
